default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>
  port: <%= ENV['PG_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scenevault_development

test:
  <<: *default
  database: scenevault_test

production:
  <<: *default
  database: scenevault_production
